---
title: "README"
author: "Jess Devine"
date: "2025-02-27"
output: rmarkdown::github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(rinat)
library(rosm)
library(ggspatial)
library(leaflet) 
library(htmltools)
library(mapview) 
library(leafpop) 
library(wesanderson)
```

## BIO4000W GIS Deliverable

```{r vegdata}
veg <- st_read("data/cape_peninsula/cape_peninsula/veg/Vegetation_Indigenous.shp")
#st_write(veg, "data/cape_peninsula/veg/Vegetation_Indigenous_duplicate.shp", append = FALSE)
names(veg)
ggplot() + 
  geom_sf(data = veg, aes(fill = National_)) +
  scale_fill_viridis_d() +  # Uses a nice color scale
  theme_minimal()

```

```{r cropping, echo=FALSE}
ext <- c(-66642.18, -3809853.29, -44412.18, -3750723.29) 
names(ext) <- c("xmin", "ymin", "xmax", "ymax") 
veg <- st_crop(veg, ext)
ggplot() + geom_sf(data=veg, aes(fill = `National_`))
```

```{r inatdata}
# Kiggelaria africana (Wild Peach)
# Virgilia oroboides (Cape Keurboom)
# Virgilia divaricata (Garden Route Keurboom)
# read in inat observations for Rapanea melanophloeos (Cape Beech)
rm <- get_inat_obs(taxon_name = "Rapanea melanophloeos",
                   bounds = c(-35, 18, -33.5, 18.5),
                   maxresults = 1000)
dim(rm)
# take only observations with geographic precision, southern hemisphere, has coordinates, isn't captive and is of research quality 
rm <- rm %>% filter(positional_accuracy<46 & 
                latitude<0 &
                !is.na(latitude) &
                captive_cultivated == "false" &
                quality_grade == "research")
dim(rm)
# make rm a spartial object
rm <- st_as_sf(rm, coords = c("longitude", "latitude"), crs = 4326)
```

```{r plotting}
ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=rm)
```

```{r reprojecting}
#Get the remnants layer
vegr <- st_read("data/cape_peninsula/cape_peninsula/veg/Vegetation_Indigenous_Remnants.shp")
rm <- st_transform(rm, st_crs(vegr)) 
#call the dimensions of rm
dim(rm)  

# remove observtaions in urban area
rm <- st_intersection(rm, vegr)
dim(rm)
ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=rm)

pal <- wes_palette("Zissou1", 8, type = "continuous")

ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=rm, aes(col = National_)) +
  scale_colour_manual(values = pal)
rm %>% group_by(National_) %>% summarise(n())
```
343 rm outside saf

```{r buffering}
#Find the localities that are not in Southern Afrotemperate Forest and add a 250m buffer
nsaf <- rm %>% 
  filter(National_ != "Southern Afrotemperate Forest") %>%
  st_buffer(dist = 250)
#Get the number of unique iNaturalist record numbers
length(unique(nsaf$id)) 
#Intersect new polygons with veg remnants and filter for those that overlap Southern Afrotemperate Forest only
nsaf <- st_intersection(nsaf, vegr) %>% filter(National_.1 == "Southern Afrotemperate Forest")
#Get the number of unique iNaturalist record numbers that overlap PSF
length(unique(nsaf$id))
314-75
```
314 rm records originally outside saf
75 rm records near saf
239 remain outside saf

```{R final}

# Define a color palette function for National_ categories
pal <- colorFactor(viridis::viridis(length(unique(rm$National_))), 
                   domain = rm$National_)

leaflet(rm) %>%
  addTiles() %>%  # Base map
  addCircleMarkers(
    radius = 4, 
    color = ~pal(National_),  # Apply color function
    popup = ~paste0("<b>National Vegetation:</b> ", National_, "<br>",
                    "<b>Observation Link:</b> <a href='", url, "' target='_blank'>iNat</a>"),
    group = "Observations"
  ) %>%
  addLegend(
    "bottomright",
    pal = pal,
    values = rm$National_,
    title = "National Vegetation Type",
    opacity = 1
  )
```

```{r all}
# Load leaflet and create custom icons for species
library(leaflet)

species_icons <- iconList(
  "Rapanea melanophloeos" = makeIcon("icons/rapanea.png", iconWidth = 20, iconHeight = 20),
  "Kiggelaria africana" = makeIcon("icons/kiggelaria.png", iconWidth = 20, iconHeight = 20),
  "Virgilia oroboides" = makeIcon("icons/virgilia_o.png", iconWidth = 20, iconHeight = 20),
  "Virgilia divaricata" = makeIcon("icons/virgilia_d.png", iconWidth = 20, iconHeight = 20)
)

leaflet(inat_data) %>%
  addTiles() %>%
  addMarkers(
    icon = ~species_icons[species],  # Assign species-specific icons
    popup = ~paste0("<b>Species:</b> ", species, "<br>",
                    "<b>National Vegetation:</b> ", National_, "<br>",
                    "<b>Distance from Afrotemperate Forest:</b> ", within_250m, "<br>",
                    "<b>Observation Link:</b> <a href='", url, "' target='_blank'>iNat</a>"),
    group = "Observations"
  ) %>%
  addLegend(
    "bottomright",
    pal = pal,
    values = inat_data$color_group,
    title = "Distance & Vegetation Type",
    opacity = 1
  )


```